#!/usr/bin/env ruby

require 'fileutils'
source_dir = '/Users/jasonko/OneDrive/ScanSnap'
source_files = Dir["#{source_dir}/*.pdf"]

file_types = { 
               'amazoncard' => 'creditcard',
               'amerasiabank' => 'bank_statements',
               'ameriprise' => 'finance',
               'axa' => 'finance',
               'discover_sm' => 'creditcard',
               'equitable' => 'finance',
               'iba' => 'health',
               'johnhancock' => 'finance',
               'jason' => 'personal',
               'lij_medical' => 'health',
               'northern_obgym' => 'health',
               'nys_dmv' => 'car',
               'nycfinance' => 'bills',
               'river_source_life_insurance' => 'insurance',
               'shangmin' => 'personal',
               'target' => 'bill',
               'ticket' => 'car',
             }

source_files.each do |file|
  puts "Process: #{file}"
  prefix = File.basename(file).split('-')[0]
  year = File.basename(file).split('-')[-1][0,4]
  type = file_types[prefix]

  destination = "#{source_dir}/#{type}/#{year}/"
  unless File.directory?(destination)
    puts type
    if(type != nil)
      puts "MKDIR: #{destination}"
      FileUtils.mkdir_p(destination)
    else 
      puts 'unknown type'
    end
  end
  if(type != nil)
    puts "MOVE - #{type}: #{file}"
    FileUtils.mv("#{file}", destination)    
  end

end
