#!/bin/sh

URL='http://www.accuweather.com/en/de/berlin/10178/weather-forecast/349727'

wget -q -O- "$URL" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $2": "$16", "$12"°" }'| head -1

curl -s http://www.wunderground.com/cgi-bin/findweather/getForecast?query=11366 | awk '/Today is/ || /Tomorrow is/' | awk '!/weather_quickie/' | textutil -convert txt -stdin -stdout -format html
echo ""
